import type { NovaNewsCriticality, NovaNewsDesk, NovaNewsStory } from '../types/novaNews';

function story(partial: Omit<NovaNewsStory, 'publisher' | 'reasons'> & {
  publisher?: string;
  reasons?: string[];
}): NovaNewsStory {
  return {
    ...partial,
    publisher: partial.publisher ?? partial.source,
    reasons: partial.reasons ?? [`Source tier ${partial.outlet_kind}.`],
  };
}

const CRITICAL: NovaNewsStory[] = [
  story({
    id: 'sample-critical',
    headline: 'Citadel expands its AI trading desk after an SEC look',
    summary: 'Models now place more of the desk flow.',
    url: 'https://example.com/citadel-ai-desk',
    source: 'Reuters',
    outlet_kind: 'major',
    criticality: 'critical',
    criticality_score: 88,
    reasons: ['Source tier major.', 'AI is doing the trading: ai trading.'],
    symbols: [],
    published_at: '2026-09-11T12:10:00+00:00',
    age_hours: 0.4,
    provider: 'gnews_wires',
    tags: ['executes', 'funds'],
  }),
  story({
    id: 'sample-critical-2',
    headline: 'Yahoo Finance: an execution algorithm halted a Chicago desk',
    summary: 'The tape stopped while the model was pulled.',
    url: 'https://finance.yahoo.com/news/algo-halt',
    source: 'Yahoo Finance',
    outlet_kind: 'yahoo',
    criticality: 'critical',
    criticality_score: 84,
    symbols: [],
    published_at: '2026-09-11T12:05:00+00:00',
    age_hours: 0.5,
    provider: 'gnews_yahoo',
    tags: ['executes', 'yahoo'],
  }),
  story({
    id: 'sample-critical-3',
    headline: 'Two Rivers launches an AI hedge fund for US equities',
    summary: 'Systematic book, weekend close targeted.',
    url: 'https://www.ft.com/ai-hedge',
    source: 'Financial Times',
    outlet_kind: 'major',
    criticality: 'critical',
    criticality_score: 80,
    symbols: [],
    published_at: '2026-09-11T11:50:00+00:00',
    age_hours: 0.8,
    provider: 'gnews_hf',
    tags: ['executes', 'funds'],
  }),
];

const HIGH: NovaNewsStory[] = [
  story({
    id: 'sample-high',
    headline: 'Machine learning comes to the trading desk at a bulge-bracket',
    summary: 'Order routing is the first live book.',
    url: 'https://www.cnbc.com/ml-desk',
    source: 'CNBC Technology',
    outlet_kind: 'major',
    criticality: 'high',
    criticality_score: 64,
    reasons: ['Source tier major.', 'Headline pairs AI with trading.'],
    symbols: [],
    published_at: '2026-09-11T12:20:00+00:00',
    age_hours: 0.3,
    provider: 'cnbc_tech',
    tags: [],
  }),
  story({
    id: 'sample-high-2',
    headline: 'Quant fund ships a new trading algorithm for open auction',
    summary: 'The house kept the human override.',
    url: 'https://www.risk.net/quant-algo',
    source: 'Risk.net',
    outlet_kind: 'major',
    criticality: 'high',
    criticality_score: 60,
    symbols: [],
    published_at: '2026-09-11T11:40:00+00:00',
    age_hours: 0.9,
    provider: 'gnews_quant',
    tags: ['executes', 'funds'],
  }),
  story({
    id: 'sample-high-3',
    headline: 'Autonomous trading bots take a larger share of overnight FX',
    summary: 'No filing, just market-structure tape.',
    url: 'https://www.thetradenews.com/bots',
    source: 'The TRADE',
    outlet_kind: 'small',
    criticality: 'high',
    criticality_score: 55,
    symbols: [],
    published_at: '2026-09-11T11:20:00+00:00',
    age_hours: 1.2,
    provider: 'gnews_agents',
    tags: ['executes', 'small'],
  }),
  story({
    id: 'sample-high-4',
    headline: 'AI analyst tools start covering the buy-side morning meeting',
    summary: 'Research notes, not an order router -- yet.',
    url: 'https://www.institutionalinvestor.com/ai-analyst',
    source: 'Institutional Investor',
    outlet_kind: 'major',
    criticality: 'high',
    criticality_score: 52,
    symbols: [],
    published_at: '2026-09-11T10:50:00+00:00',
    age_hours: 1.7,
    provider: 'gnews_trade_press',
    tags: ['executes'],
  }),
];

const WATCH: NovaNewsStory[] = [
  story({
    id: 'sample-watch',
    headline: 'OpenAI-style agents start sitting on a prop trading bench',
    summary: 'Still a pilot. Humans still click.',
    url: 'https://techcrunch.com/ai-prop',
    source: 'TechCrunch AI',
    outlet_kind: 'small',
    criticality: 'watch',
    criticality_score: 40,
    reasons: ['Source tier secondary.', 'Headline pairs AI with trading.'],
    symbols: [],
    published_at: '2026-09-11T12:00:00+00:00',
    age_hours: 0.6,
    provider: 'techcrunch_ai',
    tags: ['small'],
  }),
  story({
    id: 'sample-watch-2',
    headline: 'Asset managers test machine learning on order flow',
    summary: 'No production cutover date.',
    url: 'https://www.marketsmedia.com/ml-flow',
    source: 'Markets Media',
    outlet_kind: 'small',
    criticality: 'watch',
    criticality_score: 38,
    symbols: [],
    published_at: '2026-09-11T11:10:00+00:00',
    age_hours: 1.4,
    provider: 'markets_media',
    tags: ['funds', 'small'],
  }),
  story({
    id: 'sample-watch-3',
    headline: 'Wall Street invests in an AI brokerage stack',
    summary: 'Infrastructure first, then routing.',
    url: 'https://www.wired.com/ai-broker',
    source: 'WIRED Business',
    outlet_kind: 'small',
    criticality: 'watch',
    criticality_score: 34,
    symbols: [],
    published_at: '2026-09-11T10:30:00+00:00',
    age_hours: 2.0,
    provider: 'wired',
    tags: ['small'],
  }),
  story({
    id: 'sample-watch-4',
    headline: 'Yahoo News: $MSFT cloud is training a trading model',
    summary: 'The pairing is in the headline, not a chip story.',
    url: 'https://news.yahoo.com/msft-model',
    source: 'Yahoo News',
    outlet_kind: 'yahoo',
    criticality: 'watch',
    criticality_score: 32,
    symbols: ['MSFT'],
    published_at: '2026-09-11T10:10:00+00:00',
    age_hours: 2.3,
    provider: 'gnews_yahoo',
    tags: ['executes', 'yahoo'],
  }),
];

const BACKGROUND: NovaNewsStory[] = [
  story({
    id: 'sample-bg',
    headline: 'Hedgeweek: a small desk note on AI trading latency',
    summary: 'Regional coverage, still on this beat.',
    url: 'https://www.hedgeweek.com/ai-latency',
    source: 'Hedgeweek',
    outlet_kind: 'small',
    criticality: 'background',
    criticality_score: 20,
    reasons: ['Source tier secondary.'],
    symbols: [],
    published_at: '2026-09-11T11:00:00+00:00',
    age_hours: 1.6,
    provider: 'hedgeweek',
    tags: ['executes', 'small'],
  }),
  story({
    id: 'sample-bg-2',
    headline: 'arXiv: a q-fin.TR paper on machine learning for portfolios',
    summary: 'Working paper, not a desk memo.',
    url: 'https://arxiv.org/abs/2601.00001',
    source: 'arXiv q-fin.TR',
    outlet_kind: 'small',
    criticality: 'background',
    criticality_score: 18,
    symbols: [],
    published_at: '2026-09-11T09:40:00+00:00',
    age_hours: 3.1,
    provider: 'arxiv_qfin',
    tags: ['research', 'small'],
  }),
  story({
    id: 'sample-bg-3',
    headline: 'Finextra: banks trial AI agents on the trading floor',
    summary: 'Payments cousins stay off this page.',
    url: 'https://www.finextra.com/ai-floor',
    source: 'Finextra',
    outlet_kind: 'small',
    criticality: 'background',
    criticality_score: 16,
    symbols: [],
    published_at: '2026-09-11T09:00:00+00:00',
    age_hours: 3.8,
    provider: 'finextra',
    tags: ['small'],
  }),
  story({
    id: 'sample-bg-4',
    headline: 'MIT Technology Review: how quants actually train a trading model',
    summary: 'Explainer, still on-topic.',
    url: 'https://www.technologyreview.com/quant-train',
    source: 'MIT Technology Review',
    outlet_kind: 'small',
    criticality: 'background',
    criticality_score: 14,
    symbols: [],
    published_at: '2026-09-11T08:20:00+00:00',
    age_hours: 4.5,
    provider: 'mit_tr',
    tags: ['executes', 'funds', 'research', 'small'],
  }),
];

const COLUMNS: Record<NovaNewsCriticality, NovaNewsStory[]> = {
  critical: CRITICAL,
  high: HIGH,
  watch: WATCH,
  background: BACKGROUND,
};

export const SAMPLE_NOVA_NEWS_DESK: NovaNewsDesk = {
  schema_version: 2,
  as_of: 1_736_668_800,
  error: null,
  sources: [
    { id: 'gnews_wires', label: 'Wires AI trading', ok: true, count: 1, error: null },
    { id: 'gnews_yahoo', label: 'Yahoo AI trading', ok: true, count: 2, error: null },
    { id: 'gnews_hf', label: 'AI hedge funds', ok: true, count: 1, error: null },
    { id: 'cnbc_tech', label: 'CNBC Technology', ok: true, count: 1, error: null },
    { id: 'hedgeweek', label: 'Hedgeweek', ok: true, count: 1, error: null },
    { id: 'arxiv_qfin', label: 'arXiv q-fin.TR', ok: true, count: 1, error: null },
  ],
  counts: {
    critical: CRITICAL.length,
    high: HIGH.length,
    watch: WATCH.length,
    background: BACKGROUND.length,
    total: CRITICAL.length + HIGH.length + WATCH.length + BACKGROUND.length,
  },
  columns: COLUMNS,
  stories: [...CRITICAL, ...HIGH, ...WATCH, ...BACKGROUND],
};
