import type { NovaNewsCriticality, NovaNewsDesk, NovaNewsStory } from '../types/novaNews';

function story(partial: Omit<NovaNewsStory, 'publisher' | 'reasons'> & {
  publisher?: string;
  reasons?: string[];
}): NovaNewsStory {
  return {
    ...partial,
    publisher: partial.publisher ?? partial.source,
    reasons: partial.reasons ?? [`Source tier ${partial.outlet_kind}.`],
  };
}

const CRITICAL: NovaNewsStory[] = [
  story({
    id: 'sample-critical',
    headline: 'SEC charges ACME after FDA rejection',
    summary: 'An 8-K landed with the complaint.',
    url: 'https://example.com/sec-acme',
    source: 'SEC',
    outlet_kind: 'official',
    criticality: 'critical',
    criticality_score: 92,
    reasons: ['Source tier official.', 'Critical language: sec charges.'],
    symbols: ['ACME'],
    published_at: '2026-09-11T12:10:00+00:00',
    age_hours: 0.4,
    provider: 'finnhub',
    tags: ['filings'],
  }),
  story({
    id: 'sample-critical-2',
    headline: 'Trading halt: $CRWV after going-concern language',
    summary: 'The tape stopped while the filing posted.',
    url: 'https://finance.yahoo.com/news/crwv-halt',
    source: 'Yahoo Finance',
    outlet_kind: 'yahoo',
    criticality: 'critical',
    criticality_score: 88,
    symbols: ['CRWV'],
    published_at: '2026-09-11T12:05:00+00:00',
    age_hours: 0.5,
    provider: 'yahoo_finance',
    tags: ['yahoo', 'filings'],
  }),
  story({
    id: 'sample-critical-3',
    headline: 'Reuters: merger agreement takes private a mid-cap name',
    summary: 'Cash deal, weekend close targeted.',
    url: 'https://news.yahoo.com/merger',
    source: 'Reuters',
    outlet_kind: 'major',
    criticality: 'critical',
    criticality_score: 80,
    symbols: ['MVO'],
    published_at: '2026-09-11T11:50:00+00:00',
    age_hours: 0.8,
    provider: 'google_wires',
    tags: ['yahoo', 'markets'],
  }),
];

const HIGH: NovaNewsStory[] = [
  story({
    id: 'sample-high',
    headline: 'Yahoo Finance: NVDA contract award lifts the tape',
    summary: 'A supplier win hit the wire.',
    url: 'https://finance.yahoo.com/news/nvda-award',
    source: 'Yahoo Finance',
    outlet_kind: 'yahoo',
    criticality: 'high',
    criticality_score: 64,
    reasons: ['Source tier major.', 'High-signal language: contract award.'],
    symbols: ['NVDA'],
    published_at: '2026-09-11T12:20:00+00:00',
    age_hours: 0.3,
    provider: 'yahoo_finance',
    tags: ['yahoo'],
  }),
  story({
    id: 'sample-high-2',
    headline: 'CNBC: $MSFT raises guidance after earnings beat',
    summary: 'Cloud print cleared the street.',
    url: 'https://www.cnbc.com/msft-guide',
    source: 'CNBC',
    outlet_kind: 'major',
    criticality: 'high',
    criticality_score: 60,
    symbols: ['MSFT'],
    published_at: '2026-09-11T11:40:00+00:00',
    age_hours: 0.9,
    provider: 'cnbc',
    tags: ['markets'],
  }),
  story({
    id: 'sample-high-3',
    headline: 'Benzinga: initiated coverage with a buy and a price target',
    summary: 'First note from a new desk.',
    url: 'https://www.benzinga.com/cover',
    source: 'Benzinga',
    outlet_kind: 'major',
    criticality: 'high',
    criticality_score: 55,
    symbols: ['AAPL'],
    published_at: '2026-09-11T11:20:00+00:00',
    age_hours: 1.2,
    provider: 'benzinga',
    tags: ['markets'],
  }),
  story({
    id: 'sample-high-4',
    headline: 'Form 4: insider buy lands on $ABVX',
    summary: 'Director added after the close.',
    url: 'https://www.sec.gov/form4-abvx',
    source: 'SEC',
    outlet_kind: 'official',
    criticality: 'high',
    criticality_score: 52,
    symbols: ['ABVX'],
    published_at: '2026-09-11T10:50:00+00:00',
    age_hours: 1.7,
    provider: 'finnhub',
    tags: ['filings'],
  }),
];

const WATCH: NovaNewsStory[] = [
  story({
    id: 'sample-watch',
    headline: 'Reuters: Wall Street waits on the Fed',
    summary: 'Futures were little changed.',
    url: 'https://news.yahoo.com/fed',
    source: 'Reuters',
    outlet_kind: 'major',
    criticality: 'watch',
    criticality_score: 40,
    reasons: ['Source tier major.', 'Fresh under 2 hours.'],
    symbols: [],
    published_at: '2026-09-11T12:00:00+00:00',
    age_hours: 0.6,
    provider: 'yahoo_news',
    tags: ['yahoo', 'markets'],
  }),
  story({
    id: 'sample-watch-2',
    headline: 'MarketWatch: oil prices and the jobs report in view',
    summary: 'Macro calendar still owns the open.',
    url: 'https://www.marketwatch.com/oil',
    source: 'MarketWatch',
    outlet_kind: 'major',
    criticality: 'watch',
    criticality_score: 38,
    symbols: [],
    published_at: '2026-09-11T11:10:00+00:00',
    age_hours: 1.4,
    provider: 'marketwatch',
    tags: ['markets'],
  }),
  story({
    id: 'sample-watch-3',
    headline: 'Guardian Business: treasury yields stay in range',
    summary: 'No new catalyst, still on the wire.',
    url: 'https://www.theguardian.com/business/yields',
    source: 'Guardian Business',
    outlet_kind: 'major',
    criticality: 'watch',
    criticality_score: 34,
    symbols: [],
    published_at: '2026-09-11T10:30:00+00:00',
    age_hours: 2.0,
    provider: 'guardian',
    tags: ['markets'],
  }),
  story({
    id: 'sample-watch-4',
    headline: 'Yahoo News: $TSLA volume picks up into the close',
    summary: 'No filing, just tape.',
    url: 'https://news.yahoo.com/tsla',
    source: 'Yahoo News',
    outlet_kind: 'yahoo',
    criticality: 'watch',
    criticality_score: 32,
    symbols: ['TSLA'],
    published_at: '2026-09-11T10:10:00+00:00',
    age_hours: 2.3,
    provider: 'yahoo_news',
    tags: ['yahoo', 'markets'],
  }),
];

const BACKGROUND: NovaNewsStory[] = [
  story({
    id: 'sample-bg',
    headline: 'Hedgeweek: a small desk note on tape speed',
    summary: 'Regional coverage, still on the wire.',
    url: 'https://www.hedgeweek.com/tape',
    source: 'Hedgeweek',
    outlet_kind: 'small',
    criticality: 'background',
    criticality_score: 20,
    reasons: ['Source tier secondary.'],
    symbols: [],
    published_at: '2026-09-11T11:00:00+00:00',
    age_hours: 1.6,
    provider: 'hedgeweek',
    tags: ['small', 'markets'],
  }),
  story({
    id: 'sample-bg-2',
    headline: 'Traders Magazine: a regional house on venue fees',
    summary: 'Market-structure note, not a catalyst.',
    url: 'https://www.tradersmagazine.com/fees',
    source: 'Traders Magazine',
    outlet_kind: 'small',
    criticality: 'background',
    criticality_score: 18,
    symbols: [],
    published_at: '2026-09-11T09:40:00+00:00',
    age_hours: 3.1,
    provider: 'traders_magazine',
    tags: ['small', 'markets'],
  }),
  story({
    id: 'sample-bg-3',
    headline: 'Finextra: payments rail upgrade, no ticker',
    summary: 'Infrastructure recap.',
    url: 'https://www.finextra.com/rails',
    source: 'Finextra',
    outlet_kind: 'small',
    criticality: 'background',
    criticality_score: 16,
    symbols: [],
    published_at: '2026-09-11T09:00:00+00:00',
    age_hours: 3.8,
    provider: 'finextra',
    tags: ['small'],
  }),
  story({
    id: 'sample-bg-4',
    headline: 'Markets Media: a quiet note on closing auctions',
    summary: 'Trade-press context.',
    url: 'https://www.marketsmedia.com/auctions',
    source: 'Markets Media',
    outlet_kind: 'small',
    criticality: 'background',
    criticality_score: 14,
    symbols: [],
    published_at: '2026-09-11T08:20:00+00:00',
    age_hours: 4.5,
    provider: 'markets_media',
    tags: ['small', 'markets'],
  }),
];

const COLUMNS: Record<NovaNewsCriticality, NovaNewsStory[]> = {
  critical: CRITICAL,
  high: HIGH,
  watch: WATCH,
  background: BACKGROUND,
};

export const SAMPLE_NOVA_NEWS_DESK: NovaNewsDesk = {
  schema_version: 1,
  as_of: 1_736_668_800,
  error: null,
  sources: [
    { id: 'yahoo_finance', label: 'Yahoo Finance', ok: true, count: 2, error: null },
    { id: 'yahoo_news', label: 'Yahoo News', ok: true, count: 2, error: null },
    { id: 'google_wires', label: 'Reuters / AP / Bloomberg', ok: true, count: 1, error: null },
    { id: 'finnhub', label: 'Finnhub', ok: true, count: 2, error: null },
    { id: 'cnbc', label: 'CNBC', ok: true, count: 1, error: null },
    { id: 'marketwatch', label: 'MarketWatch', ok: true, count: 1, error: null },
    { id: 'hedgeweek', label: 'Hedgeweek', ok: true, count: 1, error: null },
    { id: 'traders_magazine', label: 'Traders Magazine', ok: true, count: 1, error: null },
  ],
  counts: {
    critical: CRITICAL.length,
    high: HIGH.length,
    watch: WATCH.length,
    background: BACKGROUND.length,
    total: CRITICAL.length + HIGH.length + WATCH.length + BACKGROUND.length,
  },
  columns: COLUMNS,
  stories: [...CRITICAL, ...HIGH, ...WATCH, ...BACKGROUND],
};
